'From Cuis 4.2 of 25 July 2013 [latest update: #1808] on 24 August 2013 at 4:26:54.71723 pm'!
'Description Please enter a description for this package'!
!provides: 'Cuis-Swazoo-Installer' 1 0!
!requires: 'Cuis-System-Hashing' 1 0 nil!
!requires: 'Cuis-CompatibilityWithOtherSmalltalks' 1 0 nil!
!requires: 'Cuis-Network-Protocols' 1 0 nil!
!requires: 'Cuis-Network-Url' 1 0 nil!
!requires: 'Sport' 1 0 nil!
!requires: 'Swazoo' 1 0 nil!
!classDefinition: #CuisSwazooInstaller category: #'Cuis-Swazoo-Installer'!
Object variableByteSubclass: #CuisSwazooInstaller
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Cuis-Swazoo-Installer'!
!classDefinition: 'CuisSwazooInstaller class' category: #'Cuis-Swazoo-Installer'!
CuisSwazooInstaller class
	instanceVariableNames: ''!

