'From Cuis 4.2 of 25 July 2013 [latest update: #1808] on 24 August 2013 at 5:15:43.51689 pm'!
'Description Please enter a description for this package'!
!provides: 'Cuis-Swazoo-Installer' 1 0!
!requires: 'Cuis-Network-Protocols' 1 0 nil!
!requires: 'Cuis-CompatibilityWithOtherSmalltalks' 1 0 nil!
!requires: 'Sport' 1 0 nil!
!requires: 'Cuis-Network-Url' 1 0 nil!
!requires: 'Swazoo' 1 0 nil!
!requires: 'Cuis-System-Hashing' 1 0 nil!
!classDefinition: #SwazooInstaller category: #'Swazoo-Installer'!
Object variableByteSubclass: #SwazooInstaller
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Swazoo-Installer'!
!classDefinition: 'SwazooInstaller class' category: #'Swazoo-Installer'!
SwazooInstaller class
	instanceVariableNames: ''!

